# Generated by Django 4.2.8 on 2024-01-01 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("answers", "0002_alter_answer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="disliked_by",
            field=models.ManyToManyField(
                blank=True, related_name="disliked_answers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_answers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
