# Generated by Django 4.2.8 on 2023-12-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1000)),
                (
                    "topic_picture",
                    models.ImageField(blank=True, null=True, upload_to="topic_pics/"),
                ),
            ],
        ),
    ]
