# Generated by Django 4.2.8 on 2024-01-01 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="followed_by",
            field=models.ManyToManyField(
                blank=True, related_name="followings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
