name: Build and Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      with:
        dockerfile: Dockerfile
        context: .

    - name: Wait for services to be ready
      run: docker-compose exec web /app/wait-for-it.sh db:5432 -t 60

    - name: Build Docker image
      run: docker-compose build

    - name: Run migrations
      run: docker-compose run --rm web python manage.py migrate
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Stop Docker containers
      run: docker-compose down
