name: Django Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-decouple

    - name: Create .env file
      run: echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

    - name: Run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py test
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
